2022Letters/backend

api/src/main/java/com/bouquet/api/post/dto/Category.java, api/src/main/java/com/bouquet/api/post/dto/Message.java, api/src/main/java/com/bouquet/api/post/dto/Post.java, api/src/main/java/com/bouquet/api/post/dto/PostRequest.java, api/src/main/java/com/bouquet/api/post/dto/PostResponse.java, api/src/main/java/com/bouquet/api/post/exception/Message.java, api/src/main/java/com/bouquet/api/post/exception/PostNotFoundException.java, api/src/main/java/com/bouquet/api/post/repository/Message.java, api/src/main/java/com/bouquet/api/post/repository/PostRepository.java, api/src/main/java/com/bouquet/api/post/service/Message.java, api/src/main/java/com/bouquet/api/post/service/PostService.java, api/src/main/java/com/bouquet/api/post/web/Message.java, api/src/main/java/com/bouquet/api/post/web/PostController.java
=> [POST] 게시글 1개 조회 기능 구현 

api/src/main/java/com/bouquet/api/post/service/PostService.java, api/src/main/java/com/bouquet/api/post/web/PostController.java
=> [POST] 게시글 삭제 기능 구현

api/src/main/java/com/bouquet/api/post/dto/Post.java, api/src/main/java/com/bouquet/api/post/service/PostService.java, api/src/main/java/com/bouquet/api/post/web/PostController.java
=> [POST] 게시글 수정 기능 구현

api/src/main/java/com/bouquet/api/message/dto/Message.java, api/src/main/java/com/bouquet/api/message/dto/MessageRequest.java, api/src/main/java/com/bouquet/api/message/dto/MessageResponse.java, api/src/main/java/com/bouquet/api/message/exception/Message.java, api/src/main/java/com/bouquet/api/message/exception/MessageNotFoundException.java, api/src/main/java/com/bouquet/api/message/repository/Message.java, api/src/main/java/com/bouquet/api/message/repository/MessageRepository.java, api/src/main/java/com/bouquet/api/message/service/Message.java, api/src/main/java/com/bouquet/api/message/service/MessageService.java, api/src/main/java/com/bouquet/api/message/web/Message.java, api/src/main/java/com/bouquet/api/message/web/MessageController.java
=> [MESSAGE] 메시지 생성 기능 구현

api/src/main/java/com/bouquet/api/message/dto/MessageResponse.java, api/src/main/java/com/bouquet/api/message/repository/MessageRepository.java, api/src/main/java/com/bouquet/api/message/service/MessageService.java, api/src/main/java/com/bouquet/api/message/web/MessageController.java
=> [MESSAGE] 메시지 목록 조회 기능 생성

api/.gitignore, api/src/main/java/com/bouquet/api/config/SecurityConfig.java, api/src/main/java/com/bouquet/api/user/dto/KakaoTokenInfo.java, api/src/main/java/com/bouquet/api/user/dto/KakaoUserInfo.java, api/src/main/java/com/bouquet/api/user/dto/Message.java, api/src/main/java/com/bouquet/api/user/dto/OAuthAttributes.java, api/src/main/java/com/bouquet/api/user/dto/User.java, api/src/main/java/com/bouquet/api/user/dto/UserRequest.java, api/src/main/java/com/bouquet/api/user/dto/UserResponse.java, api/src/main/java/com/bouquet/api/user/repository/Message.java, api/src/main/java/com/bouquet/api/user/repository/UserRepository.java, api/src/main/java/com/bouquet/api/user/service/CustomOAuth2UserService.java, api/src/main/java/com/bouquet/api/user/service/Message.java, api/src/main/java/com/bouquet/api/user/service/UserService.java, api/src/main/java/com/bouquet/api/user/web/Message.java, api/src/main/java/com/bouquet/api/user/web/UserController.java, api/src/main/resources/application.properties, api/src/main/resources/static/index.html
=> [USER] 유저 구글 로그인 기능 구현

api/src/main/java/com/bouquet/api/message/dto/MessageResponse.java, api/src/main/java/com/bouquet/api/message/service/MessageService.java, api/src/main/java/com/bouquet/api/message/web/MessageController.java
=> [MESSAGE] 메시지 삭제 기능 구현

api/src/main/java/com/bouquet/api/post/dto/Post.java, api/src/main/java/com/bouquet/api/post/dto/PostResponse.java, api/src/main/java/com/bouquet/api/post/service/PostService.java, api/src/main/java/com/bouquet/api/post/web/PostController.java
=> [POST] 게시글 조회 수정 

api/src/main/java/com/bouquet/api/post/dto/Post.java, api/src/main/java/com/bouquet/api/post/dto/PostResponse.java, api/src/main/java/com/bouquet/api/post/service/PostService.java
=> [POST] TIMESTAMP 변환 기능 생성

api/src/main/java/com/bouquet/api/message/dto/Message.java, api/src/main/java/com/bouquet/api/message/dto/MessageResponse.java
=> [UPDATE] 메시지 생성 컬럼 수정

api/src/main/java/com/bouquet/api/config/SecurityConfig.java, api/src/main/java/com/bouquet/api/config/WebConfig.java, api/src/main/java/com/bouquet/api/user/dto/User.java, api/src/main/java/com/bouquet/api/user/dto/UserResponse.java, api/src/main/java/com/bouquet/api/user/service/UserService.java, api/src/main/java/com/bouquet/api/user/web/UserController.java, api/src/main/java/com/bouquet/api/util/JWTUtil.java, api/src/main/resources/static/index.html
=> [User] user 삭제 기능 , jwt 발급 

api/build.gradle, api/src/main/java/com/bouquet/api/config/SwaggerConfig.java, api/src/main/resources/application.properties
=> [DOCS] Rest Api 문서 자동화

api/src/main/java/com/bouquet/api/post/dto/Post.java, api/src/main/java/com/bouquet/api/post/dto/PostRequest.java, api/src/main/java/com/bouquet/api/post/dto/PostResponse.java, api/src/main/java/com/bouquet/api/post/exception/PostNotFoundException.java, api/src/main/java/com/bouquet/api/post/repository/PostRepository.java, api/src/main/java/com/bouquet/api/post/web/PostController.java
=> [POST] 게시글 작성 기능 수정

api/src/main/java/com/bouquet/api/post/web/PostController.java
=> [Post] api문서 코멘트 추가

api/src/main/java/com/bouquet/api/user/web/UserController.java
=> [USER] api문서 코멘트 추가 

api/src/main/java/com/bouquet/api/user/web/UserController.java
=> [USER] api문서 코멘트 추가 및 수정

api/src/main/java/com/bouquet/api/message/dto/Message.java, api/src/main/java/com/bouquet/api/message/dto/MessageRequest.java, api/src/main/java/com/bouquet/api/message/dto/MessageResponse.java, api/src/main/java/com/bouquet/api/message/repository/MessageRepository.java, api/src/main/java/com/bouquet/api/message/web/MessageController.java
=> [MESSAGE] 메시지 컬럼 수정

api/src/main/java/com/bouquet/api/user/web/UserController.java
=> [USER] 구글 유저 탈퇴 기능 수정 

api/src/main/java/com/bouquet/api/post/dto/PostResponse.java, api/src/main/java/com/bouquet/api/post/service/PostService.java, api/src/main/java/com/bouquet/api/post/web/PostController.java
=> [POST] 게시글 설정 조회 기능 구현

api/build.gradle, api/src/main/java/com/bouquet/api/config/WebConfig.java, api/src/main/java/com/bouquet/api/interceptor/JWTInterceptor.java, api/src/main/java/com/bouquet/api/user/dto/TokenRequest.java, api/src/main/java/com/bouquet/api/user/dto/TokenResponse.java, api/src/main/java/com/bouquet/api/user/exception/NotValidateAccessToken.java, api/src/main/java/com/bouquet/api/user/exception/NotValidateRefreshToken.java, api/src/main/java/com/bouquet/api/user/service/UserService.java, api/src/main/java/com/bouquet/api/user/web/UserController.java, api/src/main/java/com/bouquet/api/util/JWTUtil.java, api/src/main/java/com/bouquet/api/util/RedisUtil.java
access, refresh 토큰 구현 (refresh 토큰은 redis 서버에 저장)
#93
=> [COMMON] JWT 구현(access, refresh)

api/out/production/resources/application.properties
=> [FIX] application.properties 파일 새로 추가

api/src/main/java/com/bouquet/api/config/WebConfig.java, api/src/main/java/com/bouquet/api/interceptor/JWTInterceptor.java, api/src/main/java/com/bouquet/api/user/repository/UserRepository.java, api/src/main/java/com/bouquet/api/user/service/UserService.java, api/src/main/java/com/bouquet/api/user/web/UserController.java, api/src/main/java/com/bouquet/api/util/JWTUtil.java, api/src/main/java/com/bouquet/api/util/RedisUtil.java
jwt, interceptor 관련 코드 리팩토링
#100
=> [COMMON] JWT Code Refactoring

api/src/main/java/com/bouquet/api/post/service/PostService.java
=> [POST] 게시글 Code Refactoring 
